# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package run by Cron

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "30 1 * * *"

env:
  TF_KERAS_VIS_MAX_STEPS: 3

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        tensorflow: [nightly, pre]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies with pre-released Tensorflow
      if: matrix.tensorflow == 'pre'
      run: |
        pip install --upgrade -e .[develop,examples] --pre tensorflow
    - name: Install dependencies
      if: matrix.tensorflow == 'nightly'
      run: |
        pip install --upgrade -e .[develop,examples] -q tf-nightly
    - name: Test with pytest
      run: |
        pytest -n auto --dist loadscope
      timeout-minutes: 60
    - name: Test attentions.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/attentions.ipynb
    - name: Test visualize_dense_layer.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/visualize_dense_layer.ipynb
    - name: Test visualize_conv_filters.ipynb
      run: |
        jupyter-nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute examples/visualize_conv_filters.ipynb
